// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7ZfJAAewp9ZFn-NlEdPwmnzNmWIogomE',
    appId: '1:1008422112612:web:665897476f842180e3be71',
    messagingSenderId: '1008422112612',
    projectId: 'integradorhub-dsm',
    authDomain: 'integradorhub-dsm.firebaseapp.com',
    storageBucket: 'integradorhub-dsm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPHFvhqCU0sH-_OQx_rOJSMcJ5AhCm7Ho',
    appId: '1:1008422112612:android:d783dfa638574b79e3be71',
    messagingSenderId: '1008422112612',
    projectId: 'integradorhub-dsm',
    storageBucket: 'integradorhub-dsm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPHFvhqCU0sH-_OQx_rOJSMcJ5AhCm7Ho',
    appId: '1:1008422112612:ios:d783dfa638574b79e3be71',
    messagingSenderId: '1008422112612',
    projectId: 'integradorhub-dsm',
    storageBucket: 'integradorhub-dsm.firebasestorage.app',
    iosBundleId: 'com.integradorhub.Biofrost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPHFvhqCU0sH-_OQx_rOJSMcJ5AhCm7Ho',
    appId: '1:1008422112612:macos:d783dfa638574b79e3be71',
    messagingSenderId: '1008422112612',
    projectId: 'integradorhub-dsm',
    storageBucket: 'integradorhub-dsm.firebasestorage.app',
    iosBundleId: 'com.integradorhub.Biofrost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPHFvhqCU0sH-_OQx_rOJSMcJ5AhCm7Ho',
    appId: '1:1008422112612:windows:d783dfa638574b79e3be71',
    messagingSenderId: '1008422112612',
    projectId: 'integradorhub-dsm',
    authDomain: 'integradorhub-dsm.firebaseapp.com',
    storageBucket: 'integradorhub-dsm.firebasestorage.app',
  );
}